
GET http://localhost:3333

###

POST http://localhost:3333/courses HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name" : "NodeJS"
}

###

GET http://localhost:3333/categories

###

POST http://localhost:3333/categories HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name" : "NodeJS",
    "description" : "NodeJS"
}